### ISSUE TITLE
Multiple choice

### ISSUE THREAD

**Issue by jrcacd** [jrizani/JRSpinner#1]
This library is a must have.

Can it have a multiple choice option?

**Comment by jrizani** [comment]
It is a great suggestion, I will do it later, for now I don't have much time, so wait for it. Or if you can contribute for this library, it is open for you..

**Comment by jrizani** [comment]
Hi, now you can multiple select in version 1.0.0 please read readme.md file to implement.

**Comment by jrcacd** [comment]
Fantastic!
