### ISSUE TITLE
can't find a way to set default selected value 

### ISSUE THREAD

**Issue by amFarrouk** [jrizani/JRSpinner#5]
is there a wya i can set default selected value ?

**Comment by jrizani** [comment]
You can now set default value after you set the items with code
`spinner.select(position);`

This code run with version 1.0.1

**Comment by jrizani** [comment]
make sure you call this method after you set the listener if any to make sure your listener called when you select the position.

**Comment by amFarrouk** [comment]
thnx for reviewing my feedback, and great job btw (y)
